# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

users = User.create([{username:'hector4213',email:'hectorpwns@gmail.com', password:'asdfasdf', password_confirmation:'asdfasdf'},
  {username:'TinyFootJim',email:'littlefeets@gmail.com', password:'asdfasdf', password_confirmation:'asdfasdf'}, {username:'JohnDilinger99',email:'johnny@gmail.com', password:'asdfasdf', password_confirmation:'asdfasdf'}, {username:'HoFoShO',email:'atl@onlyfans.com', password:'asdfasdf', password_confirmation:'asdfasdf'}, {username:'JustinTrudeasMustache',email:'justin@canada.ca', password:'asdfasdf', password_confirmation:'asdfasdf'}, {username:'LittleCoinPurse',email:'LCP00@harvard.edu.com', password:'asdfasdf', password_confirmation:'asdfasdf'}, {username:'TimCooksTerrible',email:'tim@apple.com', password:'asdfasdf', password_confirmation:'asdfasdf'}
  ])

posts = Post.create([{ title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Cheers turn to silent horror as New Year’s countdown reads -1, -2, -3', url: 'https://www.thebeaverton.com/2020/12/cheers-turn-to-silent-horror-as-new-years-countdown-reads-1-2-3/', user_id: 2 },
{ title: 'The Topical: Government Lobbyists Call For Members Of Congress To Play A Little Harder To Get', url: 'https://www.theonion.com/government-lobbyists-call-for-members-of-congress-to-pl-1846032825', user_id: 8 }, { title: 'PornHub To Delete All Content It Can’t Verify Is Really Between Stepson And Stepmother', url: 'https://entertainment.theonion.com/pornhub-to-delete-all-content-it-can-t-verify-is-really-1845887205', user_id: 1 }, { title: 'Some title again', url: 'www.bing.com', user_id: 1 }, { title: 'I just cant stop typing', url: 'www.myfingershurt.com', user_id: 1 },{ title: 'Christmas Tree Farmer Scatters Sack Of Candy Canes Before Ravenous Douglas Firs', url: 'https://local.theonion.com/christmas-tree-farmer-scatters-sack-of-candy-canes-befo-1845843774', user_id: 2 },{ title: 'Local woman optimistically transfers all 2020 goals to her new 2021 planner', url: 'https://www.thebeaverton.com/2021/01/local-woman-optimistically-transfers-all-2020-goals-to-her-new-2021-planner/', user_id: 1 }, { title: 'In preparation for Florida move Raptors replace logo with image of shirtless man shooting fireworks at an Alligator', url: 'https://www.thebeaverton.com/2020/11/in-preparation-for-florida-move-raptors-replace-logo-with-image-of-shirtless-man-shooting-fireworks-at-an-alligator/', user_id: 1 }, { title: 'Hundreds of Leafs fans demand the NHL “stops the steal” of the Stanley Cup', url: 'https://www.thebeaverton.com/2020/11/hundreds-of-leafs-fans-demand-the-nhl-stops-the-steal-of-the-stanley-cup/', user_id: 7 }, { title: 'Sony pulls broken, glitching Cyberpunk 2077 game, rebrands it as Cyberpunk 2020', url: 'https://www.thebeaverton.com/2020/12/sony-pulls-broken-glitching-cyberpunk-2077-game-rebrands-it-as-cyberpunk-2020/', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }, { title: 'Man buries dead pet rock', url: 'www.google.com', user_id: 1 }])
